{% set name = "help2man" %}
{% set version = "1.47.16" %}
{% set sha256 = "3ef8580c5b86e32ca092ce8de43df204f5e6f714b0cd32bc6237e6cd0f34a8f4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - 0001-Fix-shebang-in-face-of-short-limits.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - perl
  run:
    - perl

test:
  commands:
    - help2man --help
    - test -f ${PREFIX}/bin/help2man

about:
  home: https://www.gnu.org/software/help2man/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: COPYING
  summary: help2man produces simple manual pages from the --help and --version output of other commands.
  doc_url: https://www.gnu.org/software/help2man/

extra:
  recipe-maintainers:
    - mariusvniekerk
